---
- name: Install Jenkins
  hosts: jenkins
  gather_facts: false
  become_user: root
  become: yes
  tasks:

    - name: Install apt
      ansible.builtin.apt:
        name:
          - openjdk-11-jdk
          - openjdk-11-jre

    - name: Download jenkins.repo
      ansible.builtin.get_url:
        url: https://pkg.jenkins.io/debian
        dest: /etc/apt/sources.list.d/jenkins.list

    - name: Import Jenkins Key
      ansible.builtin.rpm_key:
        state: present
        key: https://pkg.jenkins.io/debian/jenkins.io.key

    - name: Install Jenkins-CI
      ansible.builtin.apt:
        name: jenkins
        state: latest

    - name: Sleep for 3 seconds and continue with play
      wait_for: timeout=3

    - name: daemon-reload to pick up config changes
      ansible.builtin.systemd:
        daemon_reload: yes

    - name: Start & Enable Jenkins
      ansible.builtin.systemd:
        enabled: yes
        name: jenkins 
        state: started
        
    - name: Get init password Jenkins
      shell: cat /var/lib/jenkins/secrets/initialAdminPassword
      changed_when: false
      register: result

    - name: Print init password Jenkins
      ansible.builtin.debug:
        var: result.stdout

